[package]
name = "kei"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
base64 = "0.22.1"
md-5 = "0.11.0-pre.4"
sha2 = "0.11.0-pre.4"
rand = "0.9.0-beta.1"
hex = "0.4.3"
